# Deploy to Railway
name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # Setup NodeJS
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        
    # Install packages
    - name: Install packages
      run: yarn install --frozen-lockfile
      
    # Install Railway
    - name: Install Railway
      run: npm i -g @railway/cli

    # Deploy using Railway
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
